[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = ['InsertEnter']
depends = ['denops.vim']
hook_source = '''
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sources', [
  \   'around',
  \   'nvim-lsp',
  \   'vsnip',
  \   'skkeleton',
  \ ])
call ddc#custom#patch_global('sourceOptions', #{
  \   _: #{
  \     matchers: ['matcher_head'],
  \     sorters: ['sorter_rank'],
  \     converters: ['converter_remove_overlap'],
  \   },
  \ })
call ddc#custom#patch_global('sourceOptions', #{
  \   around: #{
  \     mark: 'Around',
  \   },
  \ })
call ddc#custom#patch_global('sourceOptions', #{
  \   vsnip: #{
  \     mark: 'Snippet',
  \   },
  \ })
call ddc#custom#patch_global('sourceOptions', #{
  \   nvim-lsp: #{
  \     mark: 'LSP',
  \     forceCompletionPattern: '\.\w*|:\w*|->\w*',
  \   },
  \ })
call ddc#custom#patch_global('sourceOptions', #{
  \   skkeleton: #{
  \     mark: 'SKK',
  \     matchers: ['skkeleton'],
  \     sorters: [],
  \     minAutoCompleteLength: 2,
  \     isVolatile: v:true,
  \   },
  \ })
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = ['ddc.vim']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = ['ddc.vim']
hook_source = '''
let g:vsnip_snippet_dir = expand($XDG_CONFIG_HOME . '/' . $NVIM_APPNAME . '/vsnip')
'''

[[plugins]]
repo = 'uga-rosa/ddc-source-vsnip'
on_source = ['ddc.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = ['ddc.vim']
hook_source = '''
call skkeleton#config({
  \   'eggLikeNewline': v:true,
  \   'globalDictionaries': [
  \     '~/.skk/SKK-JISYO.L',
  \     '~/.skk/SKK-JISYO.jinmei',
  \   ]
  \ })
imap <C-j> <Plug>(skkeleton-enable)
cmap <C-j> <Plug>(skkeleton-enable)
'''
