[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown', 'rmd']

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'
if = 0
on_source = ['denops.vim']

[[plugins]]
repo = 'i9wa4/markdown-number-header.vim'
depends = ['denops.vim']
on_ft = ['markdown', 'rmd']

[[plugins]]
repo = 'i9wa4/get-git-branch-name.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'preservim/vim-indent-guides'
on_event = ['VimEnter']
hook_source = '''
let g:indent_guides_enable_on_vim_startup = 1
'''
