[[plugins]]
repo = 'prabirshrestha/vim-lsp'
if = "!has('nvim')"

[[plugins]]
repo = 'mattn/vim-lsp-settings'
if = "!has('nvim')"
hook_source = '''
" let g:lsp_settings_filetype_python = ['pylsp-all']
let g:lsp_settings = {
  \   'pylsp-all': {
  \     'workspace_config': {
  \       'pylsp': {
  \         'configurationSources': ['flake8']
  \       }
  \     }
  \   },
  \ }
'''
