[[plugins]]
repo = 'prabirshrestha/vim-lsp'
if = "!has('nvim')"

[[plugins]]
repo = 'mattn/vim-lsp-settings'
if = "!has('nvim')"
hook_add = '''
let g:lsp_settings_enable_suggestions = 0
let g:lsp_settings = {
  \   'pylsp-all': {
  \     'workspace_config': {
  \       'pylsp': {
  \         'configurationSources': ['flake8']
  \       }
  \     }
  \   },
  \ }
'''
