[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_event = ['BufNewFile', 'BufRead']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = ['BufNewFile', 'BufRead']
hook_source = '''
if executable('pylsp')
  " pip install python-lsp-server
  au User lsp_setup call lsp#register_server({
    \   'name': 'pylsp',
    \   'cmd': {server_info->['pylsp']},
    \   'allowlist': ['python'],
    \ })
endif

let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
if = 0
on_event = ['BufNewFile', 'BufRead']
hook_source = '''
let g:lsp_settings_filetype_python = ['pylsp']
'''

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = ['ddc.vim']
hook_source = '''
call popup_preview#enable()
'''
