[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_event = ['BufNewFile', 'BufReadPost']

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = ['ddc.vim']
hook_source = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']
