[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_event = ['BufNewFile', 'BufRead']

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = ['ddc.vim']
hook_source = '''
call popup_preview#enable()
'''
