[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = ['InsertEnter']
depends = ['denops.vim']
hook_source = '''
inoremap <C-n> <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y> <Cmd>call pum#map#confirm()<CR>
inoremap <C-e> <Cmd>call pum#map#cancel()<CR>

call ddc#custom#patch_global({
  \   'ui': 'pum',
  \   'sources': [
  \     'around',
  \     'vsnip',
  \     'nvim-lsp',
  \     'skkeleton',
  \   ],
  \   'sourceOptions': {
  \     '_': {
  \       'matchers': ['matcher_head'],
  \       'sorters': ['sorter_rank'],
  \       'converters': ['converter_remove_overlap'],
  \     },
  \     'around': {
  \       'mark': 'Around',
  \     },
  \     'vsnip': {
  \       'mark': 'Snippet',
  \     },
  \     'nvim-lsp': {
  \       'mark': 'LSP',
  \       'forceCompletionPattern': '\.\w*|:\w*|->\w*',
  \     },
  \     'skkeleton': {
  \       'mark': 'SKK',
  \       'matchers': ['skkeleton'],
  \       'sorters': [],
  \       'minAutoCompleteLength': 2,
  \       'isVolatile': v:true,
  \     },
  \   },
  \ })
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = ['ddc.vim']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = ['ddc.vim']
hook_source = '''
let g:vsnip_snippet_dir = expand($XDG_CONFIG_HOME . '/' . $NVIM_APPNAME . '/vsnip')
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
on_source = ['ddc.vim']

[[plugins]]
repo = 'vim-skk/skkeleton'
on_source = ['ddc.vim']
hook_source = '''
call skkeleton#config({
  \   'eggLikeNewline': v:true,
  \   'globalDictionaries': [
  \     '~/.skk/SKK-JISYO.L',
  \     '~/.skk/SKK-JISYO.jinmei',
  \   ]
  \ })
imap <C-j> <Plug>(skkeleton-enable)
cmap <C-j> <Plug>(skkeleton-enable)
'''
