version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-source: 'hadolint'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'

  json-jq: &json-jq
    format-command: 'jq .'
    format-stdin: true

  python-autopep8: &python-autopep8
    format-command: 'autopep8 -'
    format-stdin: true

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-source: 'flake8'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  sql-sqlfmt: &sql-sqlfmt
    format-command: 'sqlfmt -'
    format-stdin: true

  terraform-tflint: &terraform-tflint
    lint-command: 'tflint --format compact --filter ${INPUT}'
    lint-source: 'tflint'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  terraform-fmt: &terraform-fmt
    format-command: 'terraform fmt -list=false -write=false ${INPUT}'
    format-stdin: true

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  json:
    - <<: *json-jq

  python:
    # - <<: *python-autopep8
    - <<: *python-black
    - <<: *python-flake8

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  sql:
    - <<: *sql-sqlfmt

  terraform:
    - <<: *terraform-tflint
    - <<: *terraform-fmt
