version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-formats:
      - '%f:%l %m'

  json-jq: &json-jq
    format-command: 'jq'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  terraform-fmt: &terraform-fmt
    format-command: 'terraform fmt -list=false -write=false ${INPUT}'
    format-stdin: true

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  json:
    - <<: *json-jq

  sh:
    - <<: *sh-shellcheck

  terraform:
    - <<: *terraform-fmt
