version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-formats:
      - '%f:%l %m'

  json-jq: &json-jq
    format-command: 'jq'
    format-stdin: true

  python-autopep8: &python-autopep8
    format-command: 'autopep8 -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  # terraform-fmt: &terraform-fmt
  #   format-command: 'terraform fmt -list=false -write=false ${INPUT}'
  #   format-stdin: true

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  json:
    - <<: *json-jq

  python:
    - <<: *python-autopep8
    # - <<: *python-flake8

  sh:
    - <<: *sh-shellcheck

  terraform:
    - <<: *terraform-fmt
