[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_event = ['BufEnter']
hook_source = '''
" https://zenn.dev/vim_jp/articles/0005-search_help_with_ddu
call ddu#custom#patch_global(#{
\   ui: 'ff',
\   uiParams: #{
\     ff: #{
\       startAutoAction: v:true,
\       autoAction: #{
\         delay: 0,
\         name: 'preview',
\       },
\       split: 'vertical',
\       splitDirection: 'topleft',
\       startFilter: v:true,
\       winWidth: '&columns / 2 - 2',
\       previewFloating: v:true,
\       previewHeight: '&lines - 8',
\       previewWidth: '&columns / 2 - 2',
\       previewRow: 1,
\       previewCol: '&columns / 2 + 1',
\     },
\   },
\   sourceOptions: #{
\     _: #{
\       matchers: ['matcher_substring'],
\     },
\     help: #{
\       defaultAction: 'open',
\     },
\   },
\ })

call ddu#custom#patch_local('help-ff', #{
\   sources: [{'name': 'help'}],
\ })

function! s:ddu_ff_keymaps() abort
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('itemAction')<CR>
  nnoremap <buffer> i
  \ <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
  nnoremap <buffer> q
  \ <Cmd>call ddu#ui#do_action('quit')<CR>
endfunction

function! s:ddu_ff_filter_keymaps() abort
  inoremap <buffer> <CR>
  \ <Esc><Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
  nnoremap <buffer> <CR>
  \ <Cmd>call ddu#ui#do_action('closeFilterWindow')<CR>
endfunction

autocmd FileType ddu-ff call s:ddu_ff_keymaps()
autocmd FileType ddu-ff-filter call s:ddu_ff_filter_keymaps()

command! Help call ddu#start({'name': 'help-ff'})
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = ['ddu.vim']

[[plugins]]
repo = 'matsui54/ddu-source-help'
on_source = ['ddu.vim']
