[[plugins]]
repo = 'github/copilot.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'tyru/caw.vim'
on_event = ['VimEnter']

[[plugins]]
repo = 'monaqa/dps-dial.vim'
depends = ['denops.vim']
on_event = ['VimEnter']
hook_source = '''
nmap <C-a>  <Plug>(dps-dial-increment)
nmap <C-x>  <Plug>(dps-dial-decrement)
xmap <C-a>  <Plug>(dps-dial-increment)
xmap <C-x>  <Plug>(dps-dial-decrement)
xmap g<C-a> g<Plug>(dps-dial-increment)
xmap g<C-x> g<Plug>(dps-dial-decrement)
'''

[[plugins]]
repo = 'lambdalisue/vim-gin'
depends = ['denops.vim']
on_cmd = ['GinStatus']

# --------------------------------------
# Markdown
#
[[plugins]]
repo = 'i9wa4/vim-get-git-branch-name'
on_event = ['VimEnter']

[[plugins]]
repo = 'preservim/vim-markdown'
if = 0
on_ft = ['markdown', 'quarto', 'rmd']
hook_source = '''
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_ft = ['markdown', 'quarto', 'rmd']
hook_source = '''
augroup MyEasyAlign
  autocmd!
  autocmd FileType markdown,quarto,rmd vmap <Space><Space> :EasyAlign*<Bar><Enter>
augroup END
'''

[[plugins]]
repo = 'i9wa4/vim-markdown-number-header'
depends = ['denops.vim']
on_ft = ['markdown', 'quarto', 'rmd']
hook_source = '''
let g:mnh_header_level_shift = 1
'''


# --------------------------------------
# Terraform
#
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform', 'terraform-vars', 'tf']
