[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = ['VimEnter']
lua_source = '''
-- https://github.com/uga-rosa/ddc-source-lsp-setup
require('ddc_source_lsp_setup').setup()

-- https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua
-- Mappings.
local opts = { buffer = bufnr, noremap = true, silent = true }
vim.keymap.set('n', '<space>lf', vim.diagnostic.open_float, opts)

local lspconfig = require('lspconfig')
lspconfig.efm.setup{}
lspconfig.pylsp.setup{}
-- lspconfig.denols.setup{}

-- vim.api.nvim_create_autocmd({ "BufWritePre" }, {
--   callback = function()
--     vim.lsp.buf.format()
--   end,
-- })
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim', 'nvim-lspconfig']

[[plugins]]
repo = 'uga-rosa/ddc-source-lsp-setup'
on_source = ['ddc.vim', 'nvim-lspconfig']

[[plugins]]
repo = 'uga-rosa/ddc-previewer-floating'
on_source = ['ddc.vim']
lua_source = '''
local ddc_previewer_floating = require('ddc_previewer_floating')
ddc_previewer_floating.enable()
ddc_previewer_floating.setup({
  ui = "pum",
})
'''
