[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_event = ['VimEnter']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = ['VimEnter']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_source = '''
let g:lsp_auto_enable = 1
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_virtual_text_align = "after"
let g:lsp_diagnostics_virtual_text_enabled = 1
let g:lsp_diagnostics_virtual_text_wrap = "truncate"
let g:lsp_log_file = ''
let g:lsp_settings_enable_suggestions = 0
let g:lsp_settings = {
\   'efm-langserver': {
\     'disabled': v:false,
\   },
\ }

" augroup MyLspSetting
"   autocmd!
"   autocmd BufWritePre * execute 'LspDocumentFormatSync'
" augroup END
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']
