snippets:
  - name: ll
    keyword: ll
    snippet: ls -alFv
  - name: pp
    keyword: pp
    snippet: echo 'cd' $(pwd) | pbcopy
  # - name: (Quarto) render
  #   keyword: qr
  #   snippet: find . -maxdepth 1 -name "*.qmd" -type f -print | while read -r filepath;
  #             do
  #               quarto render "${filepath}";
  #             done
  - name: (Python venv) activate myenv
    keyword: pvma
    snippet: . "${PY_VENV_MYENV}"/bin/activate
  # - name: (Python) jupyter-lab
  #   keyword: jl
  #   snippet: jupyter-lab
  #             --FileCheckpoints.checkpoint_dir="${HOME}"/.cache/.ipynb_checkpoints
  #             --config="$${HOME}"/dotfiles/dot.config/jupyter/jupyter_lab_config.py
  - name: (Git) git graph
    keyword: lo
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>'
    context:
      lbuffer: '^git\s'
  - name: (Git) git graph --all
    keyword: la
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>' --all
    context:
      lbuffer: '^git\s'
