snippets:
  - name: ls for macOS & Ubuntu
    keyword: llm
    snippet:
      ls -aFlv -h --color=always -D "%Y-%m-%d %H:%M:%S"
  - name: ls for Ubuntu
    keyword: llu
    snippet:
      ls -aFlv -h --color=always --time-style=long-iso
  - name: (ghq) update
    keyword: gu
    snippet: ghq list | ghq get --update --parallel
  - name: (Git) graph
    keyword: lo
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n        %C(brightblack)[%ai] %C(green)<%an> %C(brightblack)<%ae>'
    context:
      lbuffer: '^git\s'
  - name: (Git) graph --all
    keyword: la
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n        %C(brightblack)[%ai] %C(green)<%an> %C(brightblack)<%ae>' --all
    context:
      lbuffer: '^git\s'
  - name: (Python venv) activate myenv
    keyword: pvma
    snippet: . "${PY_VENV_MYENV}"/bin/activate
  # - name: (Python) jupyter-lab
  #   keyword: pjl
  #   snippet:
  #     jupyter-lab
  #       --FileCheckpoints.checkpoint_dir="${HOME}"/.cache/.ipynb_checkpoints
  #       --config="$${HOME}"/src/github.com/i9wa4/dotfiles/dot.config/jupyter/jupyter_lab_config.py
  - name: (Quarto) preview
    keyword: qp
    snippet: quarto preview
  - name: (Quarto) render
    keyword: qr
    snippet: quarto render
  #   # NOTE: Without _quarto.yml, the following command is useful.
  #   snippet:
  #     find . -maxdepth 1 -name "*.qmd" -type f -print | while read -r filepath;
  #     do
  #       quarto render "${filepath}";
  #     done
  - name: update
    keyword: up
    snippet:
      zinit self-update
      && cd ~/src/github.com/i9wa4/dotfiles
      && make package-update
      && make unlink
      && ghq list | ghq get --update --parallel
      && make link
      && make vim-build
      && make pyenv-list
      && make tfenv-list
      && cd -
