snippets:
  - name: ll
    keyword: ll
    snippet: ls -alFv
  - name: (Python venv) Activate myenv
    keyword: pvma
    snippet: . "${PY_VENV_MYENV}"/bin/activate
  - name: (Quarto) Render
    keyword: qr
    snippet: find . -maxdepth 1 -name "*.qmd" -type f -print | while read -r filepath;
              do
                quarto render "${filepath}";
              done
  - name: (Python) JupyterLab
    keyword: jl
    snippet: jupyter-lab
              --FileCheckpoints.checkpoint_dir="${HOME}"/.cache/.ipynb_checkpoints
              --config="$${HOME}"/dotfiles/dot.config/jupyter/jupyter_lab_config.py
