snippets:
  - name: ll
    keyword: ll
    snippet: ls -alFv
  - name: pp
    keyword: pp
    snippet: echo 'cd' $(pwd) | pbcopy
  - name: prompt-simple
    keyword: prs
    snippet: PROMPT_BACKUP=$PROMPT; PROMPT=$'\n''$ '
  - name: prompt-ordinary
    keyword: pro
    snippet: PROMPT=$PROMPT_BACKUP
  - name: (Git) graph
    keyword: lo
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>'
    context:
      lbuffer: '^git\s'
  - name: (Git) graph --all
    keyword: la
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>' --all
    context:
      lbuffer: '^git\s'
  # - name: (Git) browse
  #   keyword: browse
  #   snippet: '!deno run --allow-net --allow-run --allow-read --allow-env jsr:@lambdalisue/git-browse/cli'
  #   context:
  #     lbuffer: '^git\s'
  - name: (Quarto) render
    keyword: qr
    snippet: quarto render
      # NOTE: Without _quarto.yml, the following command is useful.
      # find . -maxdepth 1 -name "*.qmd" -type f -print | while read -r filepath;
      # do
      #   quarto render "${filepath}";
      # done
  - name: (Python venv) activate myenv
    keyword: pvma
    snippet: . "${PY_VENV_MYENV}"/bin/activate
  - name: (Python) jupyter-lab
    keyword: pjl
    snippet:
      jupyter-lab
        --FileCheckpoints.checkpoint_dir="${HOME}"/.cache/.ipynb_checkpoints
        --config="$${HOME}"/src/github.com/i9wa4/dotfiles/dot.config/jupyter/jupyter_lab_config.py
  - name: (ghq) update
    keyword: gu
    snippet: ghq list | ghq get --update --parallel
  - name: (Mac) update
    keyword: mu
    snippet:
      cd ~/src/github.com/i9wa4/dotfiles
      && brew update
      && brew upgrade
      && ghq list | ghq get --update --parallel
      && zinit self-update
      && make vim-build
      && make tfenv-list
      && make pyenv-list
      && cd -
  - name: (Ubuntu) update
    keyword: uu
    snippet:
      cd ~/src/github.com/i9wa4/dotfiles
      && sudo apt update
      && sudo apt upgrade -y
      && ghq list | ghq get --update --parallel
      && zinit self-update
      && make vim-build
      && make tfenv-list
      && make pyenv-list
      && cd -
