snippets:
  - name: ll
    keyword: ll
    snippet: ls -alFv
  - name: (ghq) update
    keyword: gu
    snippet: ghq list | ghq get --update --parallel
  - name: (Git) graph
    keyword: lo
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>'
    context:
      lbuffer: '^git\s'
  - name: (Git) graph --all
    keyword: la
    snippet: log --graph --format='%C(auto)%h%C(auto)%d %C(auto)%s%n            %C(blue)[%as] %C(green)<%an>' --all
    context:
      lbuffer: '^git\s'
  - name: (Python venv) activate myenv
    keyword: pvma
    snippet: . "${PY_VENV_MYENV}"/bin/activate
  # - name: (Python) jupyter-lab
  #   keyword: pjl
  #   snippet:
  #     jupyter-lab
  #       --FileCheckpoints.checkpoint_dir="${HOME}"/.cache/.ipynb_checkpoints
  #       --config="$${HOME}"/src/github.com/i9wa4/dotfiles/dot.config/jupyter/jupyter_lab_config.py
  # - name: (Quarto) render
  #   keyword: qr
  #   # NOTE: Without _quarto.yml, the following command is useful.
  #   snippet:
  #     find . -maxdepth 1 -name "*.qmd" -type f -print | while read -r filepath;
  #     do
  #       quarto render "${filepath}";
  #     done
  - name: (Mac) update
    keyword: mu
    snippet:
      brew update
      && brew upgrade
      && zinit self-update
      && cd ~/src/github.com/i9wa4/dotfiles
      && ghq list | ghq get --update --parallel
      && make vim-build
      && make tfenv-list
      && make pyenv-list
      && cd -
  - name: (Ubuntu) update
    keyword: uu
    snippet:
      sudo apt update
      && sudo apt upgrade -y
      && zinit self-update
      && cd ~/src/github.com/i9wa4/dotfiles
      && ghq list | ghq get --update --parallel
      && make vim-build
      && make tfenv-list
      && make pyenv-list
      && cd -
